### PR TITLE
Fix import rule "cannot read property of undefined"

### LINKED ISSUE #28: After last upgrade error in rule deprecate/import
After plugin upgrade to `"eslint-plugin-deprecate": "^0.8.0"` the following error appears:
```
Oops! Something went wrong! :(

ESLint: 8.44.0

TypeError: Cannot read properties of undefined (reading 'name')
Occurred while linting D:\Projects\VUEIdeaIgniterEnvironment\client\src\services\AddFullDocumentView.ts:24
Rule: "deprecate/import"
    at MemberExpression (D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\eslint-plugin-deprecate\dist\rules\import.js:45:41)
    at ruleErrorHandler (D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\eslint\lib\linter\linter.js:1050:28)
    at D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\eslint\lib\linter\node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\eslint\lib\linter\node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\eslint\lib\linter\node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:795:23)
    at D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\eslint\lib\linter\linter.js:1085:32
```
Putting off the `deprecated/import` rule solved the problem. BTW, this problem was absent in the previous version of the plugin.

OS: Windows 11
node: v19.8.1
npm: 9.7.2
eslint: v8.44.0

Thanks for looking!
mario

### PR DESCRIPTION
**Pull request by ejfrancis**
fixes #28 

rules/import add null checks to fix error when trying to read property of undefined

all tests are passing

image

### CODE REVIEW

**Comment by AlexMost** [comment]
Thanks for the contribution! Going to release a new ver. ASAP.

**Comment by AlexMost** [comment]
The new version is available - eslint-plugin-deprecate@0.8.2

**Comment by cyrixmorten** [comment]
@AlexMost did all of these changes make it into 0.8.2?

Just encountered `TypeError: Cannot read properties of undefined (reading 'type')` due to `requireArg` being undefined.

The changes here appears to fix it but within 0.8.2 it still contains:

```
      const requireArg = node.object.arguments[0];
      if (requireArg.type !== 'Literal') {
          return;
      }
```

Even though the check just after `MemberExpression` is there - so looks to me like this PR made it halfway into the release somehow.

```
MemberExpression(node) {
      if (!node.object.callee) {
          return;
      }
```

**Comment by cyrixmorten** [comment]
Oh, the extra check for `requireArg` being `undefined` is at `VariableDeclaration`,.. think we need something similar for `MemberExpression`

**Comment by cyrixmorten** [comment]
Created a PR to fix the issue: https://github.com/AlexMost/eslint-plugin-deprecate/pull/31

**Comment by AlexMost** [comment]
Thanks for the contribution, the new version is available `eslint-plugin-deprecate@0.8.3`

**Pull request merged**
